CREATE TABLE TEST_SPRING (
    TEST_ID CHAR(36) NOT NULL,
    TEXT_TEST VARCHAR(100) NULL,
    NUMBER_TEST INTEGER NOT NULL,
    PRIMARY KEY(TEST_ID)
);

CREATE TABLE TEST_LOMBOK (
    TEST_ID CHAR(36) NOT NULL,
    TEXT_TEST VARCHAR(100) NULL,
    NUMBER_TEST INTEGER NOT NULL,
    PRIMARY KEY(TEST_ID)
);