DROP TABLE EXAMPLE_ENTITY;

CREATE TABLE JOB_ENTITY (
    ID CHAR(36) NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CREATION_DATE BIGINT(20) NOT NULL,
    EXPIRATION_DATE BIGINT(20) NOT NULL,
    PRIMARY KEY(ID)
);